updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
  - directory: /src
    package-ecosystem: nuget
    schedule:
      interval: weekly
    ignore:
      - dependency-name: Microsoft.PowerShell.SDK
version: 2
