
### Save-Preferences command help
# This file is for processing with Helps. https://github.com/nightroman/Helps
@{
  command     = 'Save-Preferences'
  synopsis    = 'Save registry content as reg commands to an output directory.'
  description = 'This will save all reg commands generated by Write-RegCommands and place them in a directory. It can also commit and push the changes automatically.'
  parameters  = @{
    Commit          = 'If set, commits to Git repository at output directory.'
    DeployKey       = 'Key for pushing to Git repository. Requires -Commit.'
    Format          = 'Output format. Acceptable values: c, c#, ps, ps1, powershell.'
    MaxDepth        = 'Depth limit.'
    OutputDirectory = 'Where to store the exported data.'
    OutputFile      = 'Output file. If not set, a file with the prefix exec-reg will be made with an appropriate extension.'
    Path            = 'Registry path.'
  }
}
